import { SummaryActivity } from "./types/strava/SummaryActivity";

export const activities: SummaryActivity[] = [
  {
    resource_state: 2,
    athlete: { id: 113870893, resource_state: 1 },
    name: "Morning Ride",
    distance: 73269.6,
    moving_time: 12659,
    elapsed_time: 14909,
    total_elevation_gain: 204.3,
    type: "Ride",
    sport_type: "Ride",
    workout_type: 10,
    id: 9942235344,
    start_date: "2023-09-29T06:43:56Z",
    start_date_local: "2023-09-29T08:43:56Z",
    timezone: "(GMT+01:00) Europe/Warsaw",
    utc_offset: 7200.0,
    location_city: null,
    location_state: null,
    location_country: "Poland",
    achievement_count: 6,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9942235344",
      summary_polyline:
        "si|zHaqfmBZbDa@p@oJ[qA_@mEaDgCuCa@yAaAEQr@?zBcBdGiSh_AcApJcCha@yBbJClA~@FdCvCnBjDvDjDpHrLhBdEtCxRl@`IpDxX{vAxr@i\\j]a@dAe@FaHlH`D|JdI`RpLfRlOn\\fCrNvUpz@zAbJThEBnG@fpBzCfe@lItz@f@lPG~i@eGjy@JjCr@fE|@xBrRz[vQ~u@t@f@rGC`BnAtz@faB`@~BtCtg@nHvwAzc@pmAzL\\n@XjG|LxG`I|Sxg@ThBo@ta@zQzEx@lAr`@pfBvA~TjCle@wHtLiEdHfAdN@hCcPhiAKlBBbIMb@_pAdb@eDXQTOdBiEZue@fPcBTyIyAhK`}AIXyDvBiH`OeFdh@u@bKZ?fEkDxDeBdGkGp@[dCIrDn@rY`AxAzAvKhOzB`G|C~Mp@lA|Ax@|Dj@tWbBJj@UhHjG`AGfGHNhHfAiAnLAnAdN~Wxg@jEtB|A|d@jc@TnAGzJa@jHoCpNgAhBm@nFy@fB{@hKrKdBdCbAXw@^{CXUvBbBeApGB~@p@~A~InCrl@LlG_A@c@Vc@^oFdGcdBSwAiAcBmBqByB{@i@q@c@qAgBaLwCwt@]qTT{BjEoI~@m@pCk@|@cAjqA{qB`YyErp@kN|Hg_@FqO~@}JkJwAaQsIqVoASsJfD}Sf@oFGYkBiA_OiNiKqFgEiD{@sEIoBo@iC]e@aCw@Sc@QiFMYgc@wQaEmBaA{@cAyBcEaP]gB@yA}@}@Qm@eJk^KwCh@_D|DmNhs@_qCRiBNsGWi@Psi@_@e@eBMgDgHcYy~@MqARqJKiDgBiJeEe]Ef@`BbMAn@s[gCiNx@oU{AoIgAuOv@_PbBan@|Aq@QByd@YgQC_Sm@k^e@gBXeG?sQmCqJgCcPqC}FQy@`@qw@x@wFlAsD`DmO^oi@b@yTjKolA]ub@e@_DfAo`@V_Al@w@zZ{Wj@kAg@q]nAq{A\\{DtEgUgL?wBc@gc@qLia@mNaAy@nAoIBkBh@qD?{D`R_vARq@bAa@jA_Bp@yAIqAqAmAY_BzAmNjMc\\rFsFzAkBA[oc@kwAcGmQ{Oeh@eAuCg@i@?g@e@aAeBgHik@wiBwDqL[I[gAoJ|KoExEi@NkA`BmCc@c@l@HbAWxBoE~EkDvBkHpAsE|A}CMYd@EhAkBb@c@QMr@sB^sCkAa@s@iAl@qKF{@w@_@{C",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [51.759966937825084, 18.06434327736497],
    end_latlng: [51.759912790730596, 18.064482919871807],
    average_speed: 5.788,
    max_speed: 10.58,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 156.1,
    elev_low: 115.1,
    upload_id: 10654972430,
    upload_id_str: "10654972430",
    external_id: "1f3e6259-9739-491b-b8ae-dba7fbbc8aab-activity.fit",
    from_accepted_tag: false,
    pr_count: 1,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 113870893, resource_state: 1 },
    name: "Morning Ride",
    distance: 73906.6,
    moving_time: 13241,
    elapsed_time: 15709,
    total_elevation_gain: 349.7,
    type: "Ride",
    sport_type: "Ride",
    workout_type: 10,
    id: 9922956456,
    start_date: "2023-09-26T06:42:04Z",
    start_date_local: "2023-09-26T08:42:04Z",
    timezone: "(GMT+01:00) Europe/Warsaw",
    utc_offset: 7200.0,
    location_city: null,
    location_state: null,
    location_country: "Poland",
    achievement_count: 7,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9922956456",
      summary_polyline:
        "si|zH_qfmB^hDfAb@fKIjAm@b@n@vClAtBg@Jm@RVzBk@RgB|DBtDwAhHsAfDoB|EgFX_CIaAb@m@lCb@lBiBbFmFzKgNq@uB_@SoCyGPgA`CmDt@wCw@gAh@kEC{GqDiZyFeQw@q@[eCgEmO}Pyj@mC{FFcBSkAkK}`@_AyCs@eAfAaBJoBhIcKjX{KhIuAdAJdFlCrO`C~^gKxKpAfH_CV\\pAhI`CvFn@d@xBWpDfFzB`@p@m@hDzAjA_@lAx@hGv@V_@~CLfKlBbEg@HaD|DQzXvHxIk@h@\\pB~D`x@lJf^wQvA{B~@k@dImEpGiBnBeBfEeA`Fz@`EGxReL`NcMjCq@`BTnFbDvDnAx{@tOhAlAnHpOH|BsEry@kAtxAJjE`v@xIf[s@tCf@nCxArBrCbIxVtAvC|jAfUfIHpOqDpI}EhNeAxSxEdPH~AfDhA`Az_@vJtNdBbNn@tc@oAv~@rDh_AAJiAiBcd@mY_lBo@uCoAZbi@szChAgD|EyJxCkP`Km]lDgHtEuDk@yDeAsNa@wBuAuC@mK`@sDfDaM~BcVxDuRzBiOJwBY{BnAgLnBuBvDu@jAw@p@yC|KgWbAyA~LiGlCqDlFeTxBoRdHsW[uDP_BlKcTfEwWrBwJ}UsH]LyHzm@WTuEaBYLeUpeAgAi@XsFgAgCkA{FwPoG_@iCw@iA_C_FnBcXsLeF]F{NrmAuz@juCoX`_@cBbFK`HSj@_w@t_AmeBllAaHzBg@Mo@l@slBz`@{LIc@{@~Cea@nDcm@~Cwb@@mDm@cHc@oMp@kODiHSeWwAkKj@eKCkFgNhHI\\cIvEgE~D_BLoWnK{Et@}TjMiJ`EeDpCgJ|KiCcFOyFeIiI{Bq@gXoRoRyE_EgHxEcJ\\cCz@usAg@aYa@qBiDoGaY~ZwKmq@?sHsi@w[mJlN]jA\\~OEhJUn@cAHQr@m@~Ml@pGBjFsAtI{EkBqWoD_AgIS]sFSeA_@Ym@cCe@{QuB}e@jfCya@y]iBzIeEbN{Dn@{AhSim@cDNnGGhU}@z_BK~Ha@fC}@lc@s@nDoOn^iAp@ab@HqVbByYbBiXuAgGrAeFhD@p@iCnBBbAi@x@zShq@hD`MXxB~@fAbGzQfDvYBlGg@rFx@p@_AvCcCrDInA|A~Bp@~BnAvCwI|KuH|HeBdBoCc@_@x@Jv@SnB}ElFoDtBmNfDcDC[b@?`A{Bj@WUSv@oB\\uCmAa@o@mAl@kKDu@i@g@kD",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [51.75984598696232, 18.064417373389006],
    end_latlng: [51.759886890649796, 18.064451068639755],
    average_speed: 5.582,
    max_speed: 9.69,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 157.0,
    elev_low: 102.1,
    upload_id: 10634857168,
    upload_id_str: "10634857168",
    external_id: "2e0aff85-1962-42ed-8429-6e27b52ba522-activity.fit",
    from_accepted_tag: false,
    pr_count: 4,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 113870893, resource_state: 1 },
    name: "Morning Ride",
    distance: 80895.1,
    moving_time: 14582,
    elapsed_time: 16826,
    total_elevation_gain: 336.7,
    type: "Ride",
    sport_type: "Ride",
    workout_type: 10,
    id: 9891832220,
    start_date: "2023-09-21T06:24:45Z",
    start_date_local: "2023-09-21T08:24:45Z",
    timezone: "(GMT+01:00) Europe/Warsaw",
    utc_offset: 7200.0,
    location_city: null,
    location_state: null,
    location_country: "Poland",
    achievement_count: 2,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9891832220",
      summary_polyline:
        "aw|zH{cgmBQtGB`J[nBgE}C{BoC]oAkAa@wFwFsDyE_Rs_@gDsEe@mAu@g@qDkFCs@{@_@_KuMj@ZvAxBHKfEwQpEmYnEk_@`DkYi@o@Zk@`@@rAeFvJmOvByBtb@eLdAiAxJ{[oJiOfBqK~@gAKkBHgA`BcK|@wCjBcDtWg`@dBmF`AgJAaA[SbHycAf@DDs@hDwj@WKYt@m@@{u@HhC{iAzAwMpGgfAd@sF`AeGbAqSA{FoA_]`@gGrIifD|`@|C`JxCrQgBzO}DpA_JfG_QvAoK\\g@hDaB[_CAuEnEsBvBqBnIkT~MiVdCiD?w@ZkAlFgQfIoKzQw^rRgl@xS}q@dGqQr_@wzE_@w@qVcUqIgDw@}@o@sGGaYXkI|McmBrd@c~EjE}cAxDi]hCyQh@iIpBqJ`D{E`AcG`CyFpIme@cGeTj^at@ZaBxUodEF_Ci@_BvAaGnc@gxHd@}@~@q@xUoFvBQdCb@lDrCpl@xo@tYfJjBi@tKmTz@cAl@jAuBxK{FbMOx@Hn@teBb_Cy@xeA|AnGbBrD|JjAbAxBi@lRbCj@cAvBYzc@tMAbHbN`m@xcAfClC|UdOO\\@dj@bE`t@YlHcHjc@}FxBgA|Ag@PwKiBUPmGpr@eAjGoT|`@{FkIm@C_Q|{@aFvZk@z@kCKYb@{Blg@]nnAqA`l@L|HrAzCFn@e@zFK\\s@LgCjQLpDxAdJrA|Mq@|HmExWsBlVsFxe@kBhL{@bMyGhm@OzPO~aAwv@zA_CeBaT^]pP`Czt@CbC__@biA_]d{AwDpNwTdCqFtg@aP|a@gg@|o@?r@hAtFFbCqAtU_FrvBNnDWn@~@fD@xJNBS`@uBr_B_FrBm@~@]~NaDrK_@lBsDtf@}@lBmIbLk@~Aq@zMce@bbCFx@`AdAzUtRr@t@?`@siAh`Aml@ry@cEdAe@QOw@QDc@dCO`MaAbYwOj_@o@x@oAZab@J}RpAg@Sm@`@uYdBsXuAcGtAcFbDBt@gCdBAlAa@\\Cf@|Sjq@nDjMNfBbAdA|F|QfApHbB|PAhGg@vEx@v@w@hCkC`EI~@bBpCt@`C^Vf@rBaJ`LkGzGaAb@_AvAoC]a@t@Jv@WzBmExEuD`CuPzD}AU_@b@EfAqBd@WUWv@oB^oCgAm@u@aBr@oJ@}@u@e@gD",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [51.759971883147955, 18.064329531043768],
    end_latlng: [51.7598882317543, 18.064509239047766],
    average_speed: 5.548,
    max_speed: 11.803,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 179.7,
    elev_low: 100.1,
    upload_id: 10602144085,
    upload_id_str: "10602144085",
    external_id: "b324086e-2ab1-48f1-b4ce-036936775b84-activity.fit",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 113870893, resource_state: 1 },
    name: "Morning Ride",
    distance: 70873.4,
    moving_time: 13012,
    elapsed_time: 15282,
    total_elevation_gain: 299.6,
    type: "Ride",
    sport_type: "Ride",
    workout_type: 10,
    id: 9872668521,
    start_date: "2023-09-18T06:34:07Z",
    start_date_local: "2023-09-18T08:34:07Z",
    timezone: "(GMT+01:00) Europe/Warsaw",
    utc_offset: 7200.0,
    location_city: null,
    location_state: null,
    location_country: "Poland",
    achievement_count: 9,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9872668521",
      summary_polyline:
        "uv|zHodgmBYtG@fK_@`BiHsGkAuCm@L}F{FeDkEcR{_@eDuEe@kA{@o@oDaFWmAu@UyJqMn@ZnAlBTUvDcPxDcVvDa[tE{a@c@m@^o@XDjBiGzIeNlD{Chb@eLtKs\\Ks@qIiMIy@bBqJ|@_AEuBHoAzAsJ~@_DjVo^fDcGtAiEdAwKe@c@dHscAj@M~@{RlB}VIm@i@l@iw@JjCcjA|A{MvG_gAjAuJlAwVoAke@b@}GfKwbEy@gC@_@cRe_@l@_OG{@~EaeAa@{IGsOtDaa@y@eMqDwYs@uIyCmfAiA{KoBqf@kB{VNoJtDmt@Ro@Gw@t@cIdFebAHeWW}QfCob@`@kArD}E|AwG~BV~Be@xDeAvDuBw@yK}@}SoBgIyBiQMyCN}e@zFizBrAw^l@kDp@_AdMy@v^s|@n@}J_@pItk@qrApEsKv@sCnQ_oA|Ko}AqBoAeDk@I[lFid@`Cag@nDui@`Ech@jBeOUaE|Lkx@VY|]|Mjp@j]hArTMf@gLpJiGpi@[jEc@hhAyXTyAHM^LzvA[~@sEfE_@jDgAfEq@hHN`F`ClGz@~GJzCkD|fAbRdCrKmF~A_@HXqExc@cApGkArLwAdHq@`MoBxQApCcPP^fi@AhQRvFs@lJyAbCeFvZFVlD|@k@~KVvxA\\zE^vQZhBrBjFFtSYpAsNxWc@lB{BzZ_CnjAX|[dJ|DHvWV~Bj@z@|EoInSsR^dD`@|@vJ`EzVtUJl@a_@~vEg@jDyFbP_S`p@qRhl@_R|^qIbLkGdSMxAoB`C}MfVaJ`U_A`AyCtAxEbXDdC}@|D?tAdCfRz@vBB`DjApJzAbFGpDn@dEPtK[z_@~CCDt@pKL?f@iFvUzG|OhBdN~@bOPvq@Kf@q@EG\\Hny@oDx}@aAzQ]lBPrOw@hBFdF[lBTzCE`OMhCf@|IKfFLzM`Dz@vDfFbb@`@XvJChWw@|zAOhM_@hC_Axc@WbADd@{DpJgJlTgA|@kb@LyVbBuYfBiXyAgGvAkFfDHh@eCfBOd@Jh@g@`ArSvp@pDpM\\dCx@v@bG`RjDjZ?fGi@`Fz@h@cAbD}BlDM~@d@vAx@t@v@fC\\Rh@nC}KvMiFtF]BkAbBkCi@c@p@HbAWtBiFtF{CdBsHrAwDtAiDCUVMrAoBd@UWUt@sBb@kEgCo@p@iKLeAw@a@aD",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [51.75987155176699, 18.064392562955618],
    end_latlng: [51.75991555675864, 18.0644815787673],
    average_speed: 5.447,
    max_speed: 10.102,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 176.9,
    elev_low: 100.1,
    upload_id: 10582115822,
    upload_id_str: "10582115822",
    external_id: "3b362b99-a679-4024-a887-e547914dfc82-activity.fit",
    from_accepted_tag: false,
    pr_count: 3,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 113870893, resource_state: 1 },
    name: "Morning Ride",
    distance: 68132.4,
    moving_time: 12317,
    elapsed_time: 14630,
    total_elevation_gain: 326.8,
    type: "Ride",
    sport_type: "Ride",
    workout_type: 10,
    id: 9846795397,
    start_date: "2023-09-14T06:37:32Z",
    start_date_local: "2023-09-14T08:37:32Z",
    timezone: "(GMT+01:00) Europe/Warsaw",
    utc_offset: 7200.0,
    location_city: null,
    location_state: null,
    location_country: "Poland",
    achievement_count: 1,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9846795397",
      summary_polyline:
        "wi|zHwpfmBb@fDZEh@b@rKI~@k@d@n@jCnA|Bg@Pu@TZxBk@CkAVY`BVrAWvDuAdGeAhDaB~FeGR_ACyB\\m@vCVhAcBXHzFmGbKcM@i@m@cB[Ks@gCwAqB?wAhC{DbAuDbBCxA_CtC}Bl@RjB~H`DbLf\\qTr@fA~ApBtBbAxBb@xDE`Gs@VrAb@^zKj@jAVnFlC`G|@tLVf@Tl[vAx`@lCtE`AXEHy@TMrgAjHbBKpLsCbBIdDb@~@TjD|JdGrJnFjN\\T\\U`Vg_@`AgA~c@{TdB}Aj@gBNmCkCkd@Hk@RIff@pF~GIh|@`KzOCbJ]nDZbClAfBrBlJxYfAdBpjAbUjER~CQrNgD`IwEtNmAvSxEbFRlIGxAhDdA~@vMpCpS|F~LpAtQd@v_@gAts@|CjXd@bo@QbLw@v@^vEzDjAvApAzJxAzFjErN~BhCVCnJzFr}@`WpRnJ`UyKpKuFz@u@d@cAXeBl@qXt@wBhBaAzj@dEhEd@fZrJfDlAn@f@bL~Qh@b@`XgJn]?j^~B~DzBt@rApBx]}Ez_El@`D`Nha@fEdNx@zKThKhCbTLvB@rIM`EStB_BrHQxBXboBKz@w@lBSdAU~J|@xFx@pIUZMGwEgPSg@i@c@W{@cGaAwEMqDl@gCbD{StNmBdAwL}GcAYg[`F_A{@Ey@gCeEgByAyi@oMsAf@w`Ads@eB|@iC[o~@eSKw@nA{OEiEb@aY`AyO~@kJGUmKoFaA{AaHcP{E{HSq@c@BmT}Q}FgEgW_Ys\\}X{EmDco@}i@aOwLQk@sEyl@U[sNdF{XtIoFVg_@wF_d@kDCmEh@kAG}BkI?eGpBsAA}GzBOzL{DtCgIrCmFhCagArZIVeN`D_D}@cUgR_CgAyF{@}HfBqCHsbCsp@qCc@}CBuDpAgNtIeIbH_C`Em^d_A{LvaA{ApDmA`Au@P@R_Ln@g@Q[nAsSb_@SJiAnD[?gHoIaAy@kRt@OcAkBu_@]Yo@XuFXmEES_WISgG]oLsDwIoBaJsHWi@OyBMYWDs@vAe@JkQqk@aEoLg]ogAgUqt@gf@{}A}@iCo@_AAs@_@q@eBwGqL{^_Mua@aHwSuFqRiCkIu@sBUEU_A_MbNkCnCe@LiA~AkCc@]j@BrAWfBaGjGwCzAsGdA{FfBkBS[V?dAKPqBb@UUUt@yBb@kA{@_ASg@s@w@l@{KJw@q@g@gD",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [51.75996878184378, 18.06435308419168],
    end_latlng: [51.75991262309253, 18.06445173919201],
    average_speed: 5.532,
    max_speed: 10.532,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 220.2,
    elev_low: 112.7,
    upload_id: 10554942245,
    upload_id_str: "10554942245",
    external_id: "1ba4cd79-0924-491a-bfa7-df7dbba6a5ef-activity.fit",
    from_accepted_tag: false,
    pr_count: 1,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 113870893, resource_state: 1 },
    name: "Morning Ride",
    distance: 57530.4,
    moving_time: 10767,
    elapsed_time: 16553,
    total_elevation_gain: 207.5,
    type: "Ride",
    sport_type: "Ride",
    workout_type: 10,
    id: 9827240696,
    start_date: "2023-09-11T06:27:24Z",
    start_date_local: "2023-09-11T08:27:24Z",
    timezone: "(GMT+01:00) Europe/Warsaw",
    utc_offset: 7200.0,
    location_city: null,
    location_state: null,
    location_country: "Poland",
    achievement_count: 5,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9827240696",
      summary_polyline:
        "}v|zHmdgmB@hASzEB|I]zB{BoBeCmBiAsASmAqAe@sFsFcDcEmGwL{IgReDuEg@oAm@_@wDmFIS?c@KQw@W}A}Bq@i@gByBaCwDt@h@jAhBTg@bEmQxDmVjDcYtEsa@ASe@_@@I^e@VJz@sDpAqCtC{DjD{FvBuBfAg@~Ck@~KgDpNkDl@i@dKc\\nF_RLYf@Yj@}B~@kB]?gC{Cm@QF?]q@BJFWVj@xC`DZh@d@q@bCsIz@aB_AuBCi@fW}b@Ie@aFmKG_Bf@{HQYeAYAo@EX@U[QAKhDed@VqFz@mKf@mJj@@Du@Gk@`@wEhAmSx@{KL_@POgy@h@kNmGsGmDI[{Eo_AOwAkM}l@oQmt@e@eCYgDOg@c@j@aJAw@IYs@GPF^EPsAHu@`@wCtE}M|GaDlAei@rAoCRqFjAOIs@sDOqBb@sPlAwXb@eIp@mIv@gGvBiKAi@gCoGgHoOqEqIaDgFy@u@aBg@aSmBGYh@}EAa@sDqDkA}@mEy@ioAaMmESsm@tcAoPlYw@|@cBn@}xDHkjCOYLc@nAgH@gAN{mAh[eAEeDsB}WsCOJIh@NpVMj@eMpA_G`Am@Xcl@`~@}LhRe@?LFEVkSl[cCxCsEhCov@dRyLlFcJT[Ns@pn@VtBbC`JrBbLl@nB`Ol[pApF|A~KpLvDp@lI?lBMxBDz@bClKl@zKd@vBi@vD?~@b@t@pD|B|BpBb@V|@BZ^RQtDoJjGeMnAkBdVyUzQsRjJwMt^il@p_AuiAj@i@h@EjCLPVQzH_@dH?vLNVrTfAxh@jEXNb@lB~A`DjMqTb@KhMt@NIHm@IuCJa@bFm@`ATjd@tSfCrC|@|Ad@vAh@bEv@rP`@pB~@r@jI|@^NJXIdQAlMd@vLFVTXbDC~@SdnC`GhHP`@j@SU@OnHLHj@Zm@dEBtEeGfNhDdWjHb]dHxy@vWzbCrw@f@XL`@@xGFl@|@Q|ReJfC?~HbBnHvDXpDnAzI~AlNjAzZV~DnAnLgAlBg@|Ai@bCk@tFMlJCNa@NKjADr@cAFE|Bw@pCI`APXfAXx@|@@`HD\\^h@RtJfAfN_@bExDdEzDhDlAZtDbEdCxBbBlBrA`CbGhHz@b@Hv@vDjFv@l@b@jApA|AdCbEdGxMfGxLpEfGvFvFb@A`@VVpAbAlAtAvAn@VfCnBXaCEkIPiC@gD",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [51.75993877463043, 18.064330872148275],
    end_latlng: [51.75992142409086, 18.06449037976563],
    average_speed: 5.343,
    max_speed: 11.492,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 143.9,
    elev_low: 100.1,
    upload_id: 10534430556,
    upload_id_str: "10534430556",
    external_id: "06c8e49b-3ee8-4b0a-8cc5-6de748446eed-activity.fit",
    from_accepted_tag: false,
    pr_count: 4,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 113870893, resource_state: 1 },
    name: "Morning Ride",
    distance: 74527.3,
    moving_time: 13812,
    elapsed_time: 16123,
    total_elevation_gain: 257.1,
    type: "Ride",
    sport_type: "Ride",
    workout_type: 10,
    id: 9807449633,
    start_date: "2023-09-08T06:25:17Z",
    start_date_local: "2023-09-08T08:25:17Z",
    timezone: "(GMT+01:00) Europe/Warsaw",
    utc_offset: 7200.0,
    location_city: null,
    location_state: null,
    location_country: "Poland",
    achievement_count: 4,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9807449633",
      summary_polyline:
        "uv|zHsdgmB[lH@|I[nBsDmCiCsC_@wAiA_@kGkGiEaGwOk\\_E{Fe@mAiFoGIy@_A_@gGsHsEiGaH_HkAW{DkDyFkGoNcTgVk`@?]vBqBCsByiC_SfAst@f@oEy\\yC^aIjHek@tF{i@rHa{AJeYx@kDdDkHrAqRrBmRcI_EuU_Vui@ae@sRcL{C{Au{@eTdJ}~Aq`@C[GEYzTejCNeKvAsPT}FLyHm@_CrZqqAfD}RlFcNMg@J_@nE`DtLkm@nD_ObB{KjA_b@vJwlAev@mqBkEaPq@mAWkB{BcH_FoRiFwNqFqIqAkDCq@}F{JiGmMmC}McBiF{@gFmDkKyDqHsAeBuKsJuDkBcEiDgCwF}CcFuKo|@gH}j@cA{DiK{T[}QyOiFgAu@oOeUwAmEiAwHo@aB{DqCmFu@qEcC}AqZs@mDmB}E]mBzAsVuBsQoU_e@uQqUmEaHyKaUaiAwbBmCmFu@cDUiFCwkCV_Bdr@u\\bBg@~I{@`^cWtC|`@^r@nBz@yDzz@j@zKjAbD~]~UxAtB|@bEdIoEbBMnBeBd@gBR?~OvM~CfB`GpFPr@D~Db@tBl@x@~Bz@Q|A`@rAnB_@lHxA~Ce@d^tIfm@~FbVu@@|Hr@\\|Gb[jQjg@l{@zbA|@~AJnDaDxcAbLdcAr@zoALzkAq@|I_CnN~Hx@AvHrAGnAj@jAJc@jM{AhEgAfGOfEr@`Da@`Gh@rCLrFr@dEnAxPtBpMvAtFVlEf@lWtAhG^|F`@~BIxBqC|JG~@T^r@OjEaMnFjQhFxa@~Fr[sAj`@TxDno@ptB`ClV\\ZlQlB`L}@lFtRrFbZpDfXtC|[lGzgA`@xKDrVkBlNNhBhBnFH`AsHrTtAPf[h_@zErCpA~D|Gj@vFvA`PxInD|C|Exd@~BnXh@tCjIx~@`Cn@t@`AtLUdAfIhQps@vMfn@nFtbA|EpCrPhH~w@GiDji@In@e@K{G~cAb@ZkA|KyBfGgZbd@aA`DcBpKE`AVhAk@p@xBxArHfJcE`OxEhIZ[tEkO`ChELAYi@\\f@I[DGRJfDrHPz@OMpNth@J`D`ChFvOzg@nFjRTrB|@bA~FrQjD|YBhHg@~Ev@h@s@xCeCpDMhAb@nAv@x@z@jC^Rh@|BgLfNcFjFeBbBoCa@e@z@H|@UnBkEzEwD`CmNfDkDEWXCpAoCRMp@aC`@eCiAg@s@cBl@qJFcA}@[wC",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [51.75988605245948, 18.064401699230075],
    end_latlng: [51.75989896059036, 18.064491637051105],
    average_speed: 5.396,
    max_speed: 10.538,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 151.7,
    elev_low: 100.4,
    upload_id: 10513518638,
    upload_id_str: "10513518638",
    external_id: "4882b723-3a7b-409f-9ddc-34f87d84cbb7-activity.fit",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 113870893, resource_state: 1 },
    name: "Morning Ride",
    distance: 65703.9,
    moving_time: 12134,
    elapsed_time: 13508,
    total_elevation_gain: 229.1,
    type: "Ride",
    sport_type: "Ride",
    workout_type: 10,
    id: 9787087562,
    start_date: "2023-09-05T06:39:45Z",
    start_date_local: "2023-09-05T08:39:45Z",
    timezone: "(GMT+01:00) Europe/Warsaw",
    utc_offset: 7200.0,
    location_city: null,
    location_state: null,
    location_country: "Poland",
    achievement_count: 3,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9787087562",
      summary_polyline:
        "ew|zHgagmBOzDB`JQhBMHyDuCmC{CWkAeA]kBeB_GqGgBkC_FqJ}HgQaE}F_@cA{@s@sDgF?m@Sa@w@KuEsF_C{DiDoD_Ak@}DiEmASkEcEmDqEu@e@gMkReVu`@i@i@Bc@nByAHm@A}AajC_SjA{t@FoA`@iB_\\qCUIGYd@qHhIip@bDs[Oa@qx@iW}_@aIwc@sLaA?iE~FmE@Od@Dm@MOa`D_HmGN[_@i@cLFw`@a@i@aJeAm@g@]eBkAsSa@yBw@oBeBcC_B{Acc@wRqAa@cEh@g@_@Ky@u@wb@tAo`BAcEQeBcO{{@UqKgJTiRpEp@gu@EkDs@uFiJi]w@{AsAuA}JoEiAaAiGuIkWab@A]vDsLpDuc@|@cJ_Qa}AM{Bl@k]xJm~AqCybArDaPv@uG|AmJ`@kG~@mERcD~CuJr@yAr@_A`BCd@Y|b@a|@|DkRfAcPXiBhMqGrHwF^g@X{AtAaSNaHNcA|O{i@fByH|AiJrEoRjAgHNmBHoJ]wQ{@sSqDqYcAkLQkHVoJVKKTESQoOi@yEzFeCzCyG|EnBbCKvAq@rOyKjAyBnH}QRqB?aHTq@pEpBtEl@bExCd@nAhAbInAzDvBrDjLhPlAt@`LjDfB|@PvOLV~c@rFzVaFj]oDzHq@l~@eKxB`An@Fng@o@v@P`J}IlBo@Ml@{@^OYzCwDdHoGpe@mPr@B`ChHjBrLj@jCv@pAlAl@hAKzA{AnB{@vJoWZApC~AvIjIg@zG|E`cAvF|\\fBjIp@`F~Etb@jG`q@NjIw@liDRxH~_A~|HbU|bBhJ`o@rNv{An@l[[rUFpBzGdZjArIhQts@fMjl@VnBjF~`AnEfCd@D`@d@fNfGjx@UeBfVaAhRKt@e@Cc@|JuFzw@\\P?RcAfKo@`CuAxC_Zzc@u@`Cq@tDaAzG?b@R|@Qv@SJtBpAnAtAPl@tE~EgEhOrDrFb@lALBR_@rEkOfCvEBQSc@Xf@E_@JREWXRvBxEn@dBHh@SUtBvGnExQlD|LPnAE~Az@lArB`G`Qnk@|C~KTrBx@r@~FpQjD|YFzFk@lGt@f@{@bDcCxDI~@Rr@nA~Ap@~BVHp@pCkLhNwE~Ek@N_AxAmCe@a@r@FbAGlAQf@oE~EoDvBwHrAaEtAaANqAWa@^GjAyBf@USMn@_Cd@gCkAg@s@aBl@qJDaA}@]wC",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [51.759993340820074, 18.064238922670484],
    end_latlng: [51.759893763810396, 18.06448409333825],
    average_speed: 5.415,
    max_speed: 10.962,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 146.2,
    elev_low: 100.4,
    upload_id: 10492122624,
    upload_id_str: "10492122624",
    external_id: "d27efb97-71d4-4f0c-9dad-4e7bebf7953a-activity.fit",
    from_accepted_tag: false,
    pr_count: 2,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 113870893, resource_state: 1 },
    name: "Morning Ride",
    distance: 55437.0,
    moving_time: 10101,
    elapsed_time: 11716,
    total_elevation_gain: 249.1,
    type: "Ride",
    sport_type: "Ride",
    workout_type: 10,
    id: 9760930430,
    start_date: "2023-09-01T06:50:46Z",
    start_date_local: "2023-09-01T08:50:46Z",
    timezone: "(GMT+01:00) Europe/Warsaw",
    utc_offset: 7200.0,
    location_city: null,
    location_state: null,
    location_country: "Poland",
    achievement_count: 5,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9760930430",
      summary_polyline:
        "}v|zHgdgmBBnAUrE?pIYvBeFuDaBqB]sAkA_@uFwFcDcEkGwLmHePoEsGi@sAo@a@wDgFEw@W_@o@QcGiH{AoCuEmE_ByB_ByA]b@a@]d@p@Ux@g@g@\\d@g@r@q@|CiGra@}DxSiC`JcIbPsA~DeA~GyA~Di@lCq@fJmB^gD~A{DlDmQrU{E`JK~@cMrVwHzD{UnJeB`@oOvGa@EuCxA{dAlb@{@j@kBfEsMcAml@f}Ao@zCKpBLpBVlArBbFl@vBd@xDH`DO`DyItgA[zFItHNfLbCx_@uQlHul@j[r@rIRdAv@rArErEdApIXrFdCvHAf@kUxTkAx@qPxJ}q@x_@uLzI}IjDSQuEui@eCwOyCuUYoD@wAJo@lEqF`Q_GsGc{@eA_O?cA`M_Dz@cAjImOnq@ud@oYihAQoBAmFIe@_Cj@qCbByCb@qAbAo@RyBHaE_AwB@mFnAuD|Cm@AQe@uCsdCFo@pDkKNgBsDolAhBwkAF]l@KbTz@vJqCdJo@gFstBJQrEgBfFk@P[e@{KgA}DWsEc@uByBin@Le@lBRqBOOTS[M?@w@DKj@ZhAHT_@p@mWIaDxh@swAfPod@bGwOjE?jE{FRGbe@hMl^tHbz@~WD\\b@OQs@l@cGpAkUbBqb@vBw_@HcYT_Bf@mBjC_F\\yAjAwQhBeNfAmMnD_PzAaEz@yA`GyHxCaGhEiH`BwDfHoMbAiAtYoU|DqB`f@qKxSw@`W_@`Cs@zNkHf@a@nBsD~@o@|G?j@TdASfDFhAfHb@hAlGfXlGpV~M|n@bFvaANh@jLdGtIlDl}@_@pDvGPfJ^pAn@n@jj@xAxi@fBnAL`DjAnBZPf@YzOeCnq@N|LdBnl@XdEKj@yBr@aC[}CtD_Ah@{@@qDa@{AbAqIt@mKhD}Dr@m@G{AaA}A_@oK_@g@\\wOxDsBt@qAfByBRsU`MkDrDkD|Gm@Au@jA]s@\\`@IYLDIQTHlD`ILp@WU|BpHtJf_@N~@AlBVf@^\\fA|CpC~JhHtT`FpPnBrHL|AXf@j@XZvAdFdO|@nHjBvP?jGg@fFVCd@`@@PgAfD_ClDMz@XfAjAlAx@jCXLb@fBA`@cJbLyGbH[?kAbBwCYYr@J`AKrAMVqE~EqDvBwCx@oCVeEvAqAP}AUQZ?~@MPsBd@SUUv@wB\\wA}@k@Kk@y@kAn@iKH}@_Ac@wC",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [51.759959142655134, 18.064332799986005],
    end_latlng: [51.75989259034395, 18.064477974548936],
    average_speed: 5.488,
    max_speed: 11.558,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 137.8,
    elev_low: 93.7,
    upload_id: 10464397092,
    upload_id_str: "10464397092",
    external_id: "509e4e6c-785d-486a-8329-86657fc68f14-activity.fit",
    from_accepted_tag: false,
    pr_count: 1,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 113870893, resource_state: 1 },
    name: "Morning Ride",
    distance: 58155.1,
    moving_time: 10278,
    elapsed_time: 11881,
    total_elevation_gain: 119.9,
    type: "Ride",
    sport_type: "Ride",
    workout_type: 10,
    id: 9644417844,
    start_date: "2023-08-14T06:35:24Z",
    start_date_local: "2023-08-14T08:35:24Z",
    timezone: "(GMT+01:00) Europe/Warsaw",
    utc_offset: 7200.0,
    location_city: null,
    location_state: null,
    location_country: "Poland",
    achievement_count: 35,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9644417844",
      summary_polyline:
        "ui|zH{pfmB`@nD`@Ab@ZnCFbGUDT?l@n@tAvAdZfBpPnBdTvAx[TdI^lCdCdW|BbXbB|XlLdiArUpxAb@fEq@na@QpCoIt_@a@p@wD~Cy@zAYvAiA~JY`Is@x\\Ax_@IrO_A`L{C~WOxByDxeAmAxTuNlcBXfSLH~Iw@hMqD`By@nAmBhI_P~CoFxJiKlQeQlHyFj]mZl@u@|AsCZWvZsLn]e@pDYVNNz@\\nb@cC~X?^NXzGdCb\\|IdNtC~EJT^D`@`@hLn@`LLh@ZXdMEPJzp@XJTr@~Ig@pBgAtUqDxdAw@tRAdBZb`@|@`KpA`Yj@rFZ~JtApL^jB`@~@zCtEPf@~QjxATxAn@xB\\xBPhBFhBSvKFjAdYv~@lCxFr@dArT`BDZC^Rz@ZtEjJ|^AVUHANn@f@jN~Uz`@pk@tBvCd@b@rGxJtG|Hr@`BnC`J`AjBti@`o@|@Zn@@tLaE`B]hThXfBbBlNrAtCf@h@EvMjAVPZGbMhATPTG`Hl@fAVf@b@|@L^c@TA`L|ALVRpIhA`FH`AAvB]~HUbBVd@Jn@IZECDDEG@LMKLPf@Fp@`@NI`@kCTc@R}@^eF|B}PEKeCAsFZ_@iODoBMKKHMlAOZuAhBy@TgHu@M]s@EUSYZ}@CyH{@ab@gD]QUFqJ}@I??TIBoB[q@g@uPgTgD}D}AXuLfEsAKa@WqS}UgUsX_AkBeCqIs@iBmGkHyFqIyBuC_a@qk@mCcEiKsQaAoABYTE@SqJ}^WcFUk@Hi@GU}TcB[_@_DaHcY{~@I}@T}KGsBWyBsAcGkRczAiDwF_@w@_AcGw@qGWqJq@qGsAmYy@wJ]w_@BmCTaCbBif@p@_PLgDGc@|@iU|@wSPsATi@?y@]kDYeCMY_q@Yg@QiLGSOOo@q@aLg@iLKk@QS{EGgO{Co\\kJgFyBIY?a@|BmX[}a@MoASYQE]PoFT_[d@eZrLm@l@uAfCc@h@w[zXkKlIePbPeKrKq@~@yLvUgA|AuAp@iN|DeGb@u@@MSYgPHmCdIi_AdE{h@n@eNxD{eA~CcYdAyLHoEBkh@hAkh@`ByMp@uAbEoDh@_AjIq_@NaBr@ec@GgAc@yCaUgvAiLkhA_@gE{B_]mBqTkCkWiBae@kE{c@q@oKo@}PYEa@s@Ay@GGaGRsCI}@w@c@aD",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [51.759867779910564, 18.064381582662463],
    end_latlng: [51.7599003855139, 18.064463138580322],
    average_speed: 5.658,
    max_speed: 9.118,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 137.4,
    elev_low: 115.0,
    upload_id: 10340654821,
    upload_id_str: "10340654821",
    external_id: "8cb19a8f-49bd-4779-b567-55330d7f5159-activity.fit",
    from_accepted_tag: false,
    pr_count: 19,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 113870893, resource_state: 1 },
    name: "Morning Ride",
    distance: 63174.7,
    moving_time: 12039,
    elapsed_time: 18393,
    total_elevation_gain: 170.5,
    type: "Ride",
    sport_type: "Ride",
    workout_type: 10,
    id: 9493217349,
    start_date: "2023-07-21T06:13:58Z",
    start_date_local: "2023-07-21T08:13:58Z",
    timezone: "(GMT+01:00) Europe/Warsaw",
    utc_offset: 7200.0,
    location_city: null,
    location_state: null,
    location_country: "Poland",
    achievement_count: 5,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9493217349",
      summary_polyline:
        "yv|zHmdgmBUdHBtIYtB{DiCwBaCy@sBeAY{FyFyC{DmRg`@iDyEc@iAs@g@qDcFMaA_Aa@yJoMn@\\|AlBlEsRdE_XlEa_@dDiZa@k@\\o@Z@dAiEdKqPtBmBvb@eLn@k@|P}j@bAsCl@k@dBmFf@o@hDyKy@nBqBjHsBpE[vAq@`@]fA`@gAp@q@zAsEuE_FgAlY}AvFbF`IxCuItAqE`CnEDOWa@Zd@IYFK`@ZbDtHFj@SSdBpF~EbSpD`MNdAExAVt@\\V~AjEbQnk@jDhMb@nCp@l@dG|QdAnHbBvPBlFg@dGt@j@u@pCeCtDObAn@fBp@l@rBbGAb@k@dA`@hAXFxp@dwBxA~ENjANLVbBf@l@dApCxe@f}Azs@z}B~Wlz@b[nd@tG|Jz@tACX`@B`HfKvNvTpAzAX]bAjBvKp@`CXNo@CwMT]~@\\jJrKnB{FxS}^dAc@tK}@`Ae@`AkARHhIj_@lGbWnEhTjAlGjKxU~@dEx@|G\\dAt@|@`FzCtBdDdL`[nGbWzMvjARvKUrWfD`@|AvBlAZzBNrB]`BTcA`p@~FbYj@|DzNbu@zEtGpUbX@Zb@TENrCbE|C`CPh@~HdKfCxBjD|BvCdAhCV`JMtJjDPtKA~G_DtiAe@`K@hCeAzZEnGrTh|D`DhoAd@pYMpAXp@h@xVVnAJYLC`@lAOf@rMtZj@t@KbZS|@gClCCb@nDf@XrJrAlGg@rMh@hB[rAUH~A`@hA_Az@qK|BuPcBQ}GZW}RYLMfAW`@wA`Bm@PkHo@KYiAW]TmBKyw@eHO\\gB[y@q@{DaFE{@eMyOWTu@u@g@?oN|EwBg@wi@oo@}@iB}DcMcG_Hqn@o}@uMcUmA{AZS?_@iJi^m@}I{TcBcE}H}Xu~@I_ATuK[cFyAuGeRyyAUs@}DmGsBqOWcJs@}GoAgY{@_K[i_@pEgrA`Bi_@`@kCaA_Jor@k@_LEg@gAwAcY[_A}EGkOaDs[_J_G_COe@DiA|BoV_@}b@M_Ae@YqD`@u]h@wZzL_DzEyg@bc@k\\v\\{NlXcAnA{PfFeIVWuRvO}kBfFotAbFuf@Lcp@lAch@`BkMl@kAfFaFnIq_@NuAXsL\\sVwVg~AcK_bAcC}]sA_PwEmf@mBaf@yEog@qAwX[Ee@w@?aA{F\\cDMw@o@a@gD",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [51.75992905162275, 18.064478561282158],
    end_latlng: [51.75987741909921, 18.06451384909451],
    average_speed: 5.248,
    max_speed: 9.954,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 147.1,
    elev_low: 100.1,
    upload_id: 10180787433,
    upload_id_str: "10180787433",
    external_id: "5e4e3f91-2d34-46f1-b0f5-eb37f2a892a2-activity.fit",
    from_accepted_tag: false,
    pr_count: 3,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 113870893, resource_state: 1 },
    name: "Morning Ride",
    distance: 57836.8,
    moving_time: 10402,
    elapsed_time: 15204,
    total_elevation_gain: 256.6,
    type: "Ride",
    sport_type: "Ride",
    workout_type: 10,
    id: 9473516304,
    start_date: "2023-07-18T06:21:57Z",
    start_date_local: "2023-07-18T08:21:57Z",
    timezone: "(GMT+01:00) Europe/Warsaw",
    utc_offset: 7200.0,
    location_city: null,
    location_state: null,
    location_country: "Poland",
    achievement_count: 4,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9473516304",
      summary_polyline:
        "_w|zHgdgmBSfHDpIUvB{FoEwAaBYmAiA]{FyF{CaEwGeMsIaRiDoEe@oAy@o@mD}ECq@aAk@aGiH}BkDl@ZrAnBL?bFmTjEqYhHwn@p@cGa@y@Zc@ZLF}@b@}A~AoD~GsJLg@vBiCtAs@~TiFnJqCn@c@lKm\\bDsLlAmDr@g@XuA|@yBWo@sB}BtAhHo@`Bm@b@eFhQ@RdEdG|CnHRr@?l@NHz@g@Re@tC}NI{AN}@^c@j@BjEaIbEmDtSuKvCc@x@{Af@YjR}Eb@[vKd@dB`@zA`Ar@?lQaFxHm@fBgAjF^~@i@pCsDpCVzB{@aCwt@M}KFeEfBgg@^cRBk@PUGg@UQ{AGaGuAsS{@iKK}r@_Cy@So@cAUmBC_H_DaHm~@\\{NsG}FaDK[cFsaAaMgl@eRev@iA}Hc@ZoLEeBRcAv@eBbDo@p@cRxIim@|Ase@lK}CtAk\\lXwHhNyBzEwHfNmIlLuA~DkDfOoArNeBbNkAfQ[rAoClF{@tDI~XuBh_@eCxk@{@|No@dFoy@{Wi_@}Had@eMSR_@GcE`GmEHYb@MKSt@k@rAqC|Hw@tCsx@fyBKj@JvDs@nVe@Nu@Ge@]QL@n@\\NF~@xBfm@h@~BZ|E`AlDb@hLbFN\\^^tXlBhr@TJjWiHtLwDdC`y@rA|UN|FVjBfBvGv@|EUb@uEdBaAlBYjCrApIkJfHcU~Ymt@|z@yAdA_BZWt@yAn@eApAaAbDc@zCCp]UlDq@pBo@|@mErBEdBzAdlAbBKdDyCbFcAhBCvE`ApBMt@UjAcAnDk@xB}AzBa@FrFTfCjZxjAWeA[@cp@|c@}@dAsHbN_@^sMbEvIplA_QdGeEnFOj@?fBNhC|C|VzBpMfFhl@lJmDzKeIhfAmm@rUgURU?_@iBwEe@sB[gG{@mH_D{CoBqCeAoKpm@u[xP_HcCg`@OwJLaJtJspAJoDOuCa@_DwDcLKaBFiBt@eD`l@u|AlMx@`@[pAeD~@u@huBuz@nG_Dp@o@zLuVEg@nFyJnO}RnCwCbFiDpCk@r@eKbC_InAcIv@{BlI_PdC{IbEaTpFw^dAmFf@{AUUn@TLy@e@e@d@ZL[LFrK`LpA|BrG~Hn@BXzAfDtEx@j@f@tApD`F|IzR`FjJvD`FlGrGz@N`@|AfCnCbAd@hBdBV@RuBCsHT{I",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [51.75995201803744, 18.064307067543268],
    end_latlng: [51.759911365807056, 18.064426761120558],
    average_speed: 5.56,
    max_speed: 11.692,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 137.9,
    elev_low: 94.3,
    upload_id: 10160038857,
    upload_id_str: "10160038857",
    external_id: "a2be90a0-d3fb-42cc-9951-640b964cc760-activity.fit",
    from_accepted_tag: false,
    pr_count: 3,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 113870893, resource_state: 1 },
    name: "Morning Ride",
    distance: 56330.9,
    moving_time: 10781,
    elapsed_time: 12400,
    total_elevation_gain: 139.4,
    type: "Ride",
    sport_type: "Ride",
    workout_type: 10,
    id: 9448606452,
    start_date: "2023-07-14T06:28:12Z",
    start_date_local: "2023-07-14T08:28:12Z",
    timezone: "(GMT+01:00) Europe/Warsaw",
    utc_offset: 7200.0,
    location_city: null,
    location_state: null,
    location_country: "Poland",
    achievement_count: 0,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9448606452",
      summary_polyline:
        "yi|zHiqfmBb@tDb@Cd@^hCHzC[nBB@dAp@tAdA~VhFhi@lBhe@jGvo@`Ch_@fLfhAtUzxA^dDq@z`@QjDqIx_@g@x@_EnDo@rAeBdNkArh@@f[CjMIdDw@bJsDl]{DtgAc@fJaArMuMz|A^vS`Js@jMoDvAo@pAgBjMmV|AkB`[e[`IoGb\\cY`AcA~AuCb@e@nZsLt`@s@|ASTVJl@\\nb@cCpYNd@fGbC~[~I|NzC~ELTf@HtAlA~VHj@`@`@p_Af@L^v@vI]|@Oz@_AvRsF`~A^x_@x@rJtA~Yj@pFXzJzAdMZbBdDnFh@rAvQhwAdAxE\\rBVvBFjBUlKFpAjUzu@nChIhClFf@j@rTjB?bAP^X~EbJf^Jh@Cr@vLhSjEpGlJdNtSbZ|AhBtGxJbGdHbA`CdCpIz@~Alj@vo@bBNfBy@~KeD\\RrF|GfIrKpCdDn@b@hP|ApAZb@Gn\\zC`AVd@GdGj@hBr@lA\\h@i@tLlAZvJlAjFFv@GvCo@rKVNPd@Cn@Zj@YCJWl@LPZP`BbAj@h@FL[RyEr@kGGqAa@_ABYQiAhAyJVOLo@GKb@^lA^|Fz@b@Z~AZp@?^wMUy@q@Hc@]uAUu@?uBq@q@Bu@c@e@Ng@YoAK}JMLlBI@EuABeCU@ESJsGBmFCmHi@w@sM}ZNq@w@aBOuAa@aOk@}WUgBaDowA}Ba_@DoA}AyYeDoh@[sHgA}Nk@aM{C_g@S{FLyHfBwi@tBqv@d@kQBiESuNaK}CqGB}@NoCa@{CcAuA}@_FcE}FwHsC}CYi@a@UIWUOaA_BSGo@iASIiD{E{AeBw@q@kCoDiHgIeEuFiEiTqPc|@o@aCHoI~@{e@uBQuBZcCWy@[q@qA_@]uC]We@TiR?}IOeEyMqjAiA{DiEwQ}KcZm@sAaAqAuFmDo@}@[aA{@qH}@yDgKkU}B_LyIw`@iCiL_HwYSEkAtAwAj@qKx@g@Q[hAgFtImLvTWLgAhDWAuIyJs@YQFIZ@zMMj@uCYk@PgDe@y@r@kAhBM}@k@iA_@]kAM}p@eEmb@qAgMFof@uMm`@aNgB?eb@mNwGwCkLcCmG]uNoF?mEj@iZAcBuVc}Au@_GkJo_AmCs`@aG_o@kBsd@kEed@s@_Lo@qP[K]m@Aw@MKwFT}CI{@}@_@yC",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [51.760021755471826, 18.064428186044097],
    end_latlng: [51.75991262309253, 18.06445668451488],
    average_speed: 5.225,
    max_speed: 10.928,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 145.9,
    elev_low: 115.1,
    upload_id: 10133668091,
    upload_id_str: "10133668091",
    external_id: "b4dd3c5f-63fd-4d29-9309-02c2002b3d64-activity.fit",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 113870893, resource_state: 1 },
    name: "Morning Ride",
    distance: 65908.8,
    moving_time: 11977,
    elapsed_time: 14104,
    total_elevation_gain: 274.1,
    type: "Ride",
    sport_type: "Ride",
    workout_type: 12,
    id: 9423304098,
    start_date: "2023-07-10T06:24:38Z",
    start_date_local: "2023-07-10T08:24:38Z",
    timezone: "(GMT+01:00) Europe/Warsaw",
    utc_offset: 7200.0,
    location_city: null,
    location_state: null,
    location_country: "Poland",
    achievement_count: 6,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9423304098",
      summary_polyline:
        "{v|zHo}fmBSpD?`GUhB{DsCwA{A}@iASgAeA[qBmByC{C_DcEgGoLuHqPqEqGa@iAo@c@sDcFGw@gAk@cGqHqA_CqBwBiByAcEwEY\\a@]f@v@Up@i@_@\\`@e@d@w@rDsG|b@mDrQoC|JuHhOoAfD}AbJ}BbHk@tJ{APmFxC_FhFyNjR}EfJAv@uMbWmHnD}UlJOXSGuP~Gq@EwiAne@aAp@{AzDWPwLiA[Lgl@h}Ak@|CE~BN~AxD~K\\tCJzCSjFoIheAa@lHGzIHbI`Cpa@aQ`Hcm@n[t@tIThA|AxBrDrDv@jH\\tGbCpHGj@gVtU}dAnl@sLvI{J|D_GzDC`@dApKZl@tCd_@PnCCdFHbDxCp\\?|@nAdPBrAUTR``@KfAs@DwD`B_QhEm@X@d@cBjAVhGZh@bAKTRtA|Dj@lDLbEIzA_C~HiYdMe@UoFeGu@c@cTY_Kd@sDOgB{@kHcGgGkB}EcC_EZkIzB_CPqLiCa@LkZgImAZc@f@GbBnA|GXlEB|DyApg@YrB]lG}@tIkDxRkApIqd@dvDkH`w@?|E~BhZrBfTykAyFwNxC{^xJwGXgGi@iK|BaFtAITG`EHhAvY`~BtJzeBtExCdENf@\\CvDHh@QhFXhJlA|KKh@`St_BfDjZlH`k@|@hIOPDdA~@lAdA~@dBX~DqA`DPSpJQXu@L_@rBVHNt@h@ELWVgGZwVjE{dBjAy`@Tc@Qu@x@s\\b@mJ`CeV_@[bDs\\vMqpAfCgUvM__AjBgKF{CfA[JYd@n@hGb@f@OTc@`FoVjAeLnB{IhA_IjC{]k@YxDc_@rHg^tAwErSo^bk@a}@rT{]l[gh@zCqJxf@qdBvAgDnEmFhBaEfAyGO}@k@]|AeAXF\\o@Iq@`@uChA}D|DuG`@c@r@Mb@uAtDkB^?n@u@haAcaBj\\hVxr@|J|Is@jBf@hFKhT^T`@HtCRr@fRoItN}H|Gq@`MyDrIaAFk@aGiO_I{UeHiOm@uBi@cJe@cYWyToBya@KeGVAT_@|Dq@xEaCtdAgw@vNe\\d\\uv@~Psa@nI{KdFoF^J@k@`HcHb@Er@sAfZk[x@s@pqAoo@dAQtAcADm@uDoWm@cI_BaM{@kEcB}DuHuLuDgDwBuDwBaCq@CK{A`@iCnAkEbCga@fAcKlSu_AdBsGz@Tp@eAnCpDvDlCXuBRcS",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [51.75999769940972, 18.06431008502841],
    end_latlng: [51.759911281988025, 18.06444394402206],
    average_speed: 5.503,
    max_speed: 10.446,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 136.8,
    elev_low: 98.5,
    upload_id: 10107071042,
    upload_id_str: "10107071042",
    external_id: "60d96323-ff22-483a-912c-19f67ec2743f-activity.fit",
    from_accepted_tag: false,
    pr_count: 1,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 113870893, resource_state: 1 },
    name: "Morning Ride",
    distance: 54935.8,
    moving_time: 10084,
    elapsed_time: 11655,
    total_elevation_gain: 203.2,
    type: "Ride",
    sport_type: "Ride",
    workout_type: 12,
    id: 9404584114,
    start_date: "2023-07-07T06:28:48Z",
    start_date_local: "2023-07-07T08:28:48Z",
    timezone: "(GMT+01:00) Europe/Warsaw",
    utc_offset: 7200.0,
    location_city: null,
    location_state: null,
    location_country: "Poland",
    achievement_count: 0,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9404584114",
      summary_polyline:
        "cw|zH{zfmBIdA?~GSxAKHyBsB{BeBoA{AWmAQO[KYJQjAFz@El@wAbFkQ~x@_BdIy@zI{Bn_@yBzIDhAr@BnC~CbBbDzDlDdEvGlB`DbBzDl@nClBpNl@fIrDvWAZ_wAzr@{[`][b@Ol@g@ByG`HEJFZOBYKiHbImDfEsBjD]t@Ih@SNoAnCcFzLgB~Eoj@lqAkBdEq@t@mbAdu@uBnAoD~A}Cd@MPCXW]Q@?g@c@GO\\YHoDf@?l@[Tmi@fMgCp@iClA}CrB{A|AgE`GeP~UcHtFoAxAsDjGiEvI}RvYuwAhbCyAbBe@DeD~AQZOv@iAb@qAfBmAvBw@~Ak@dBs@dFAn@Q^_@EyAz@BVXCPPNt@g@jDk@bCqBdEuCxDk@`@uAhDyc@x|AyF~QqZpf@Yh@G^g^hk@ia@bo@uPnYsAjCeBvFmGxYi@`DqD~]FT`@N?NW~BqB|Xy@fGeChL{@|IkFhW[t@i@NcGSe@m@Q\\k@AWTGhDsAhIY`AuMz~@IbBgB~MwN`vAwC|Z@L\\NiB~Pc@|FU~FUnH@zB[|HHBIh@IdD@b@NVETWPaAt_@dA}_@RMBOSo@v@s[j@oLxBcU_@]jRyjBt@kHh@kD|@mJnM{}@XgAvA{IFaD`AIN_@V\\Wt@Rn@^Ih@m@ZKbEN\\MRk@vEkUtAgMvByJdAmHdCg]m@WL[fDu]f@sCpGeZnAiEbC{EtNoVr^kk@db@eq@DYzZ}f@v@oBjCwI|e@obBvAiDr@m@dDkEbB{D`AuGOy@e@KEWbBaAVLDUPQC{@ZkCZyAj@cB~D}Gb@c@b@CRQ^mAj@c@fCeA^ApAeB`EsHxCsEj^ym@rIaNtK_RbG~EpSpO`c@bGnNzBrAB`Go@~Cb@fDQpCXxPH^^PjDBPNHpSeJ|L{G~Gs@~KsDtKoACc@wFqOIOY@iDaKkCeIoH}Oi@}Bc@sIc@oVCiLUyF@mAgA{Vk@qJI_GXCT]bEu@zEeCb`Acs@hC_Cf\\_v@fP}_@hD}IvFqMf@_AD]nA_ChHiJ|FeGPNJo@xDaEfB_B`@C\\{@~AyAtWaY~@{@nvAcr@HS?]wDgWo@mIaBgMy@cEcB}DuHuLgE{D}AwCyAeBa@Mc@e@[FKe@HwArByHdCma@TyCn@_FnS}_AbBwGl@\\^QZq@f@r@nB|Br@RT\\jBpAZuBCoJLoBDqD",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [51.76013784483075, 18.06429147720337],
    end_latlng: [51.7599265370518, 18.064458360895514],
    average_speed: 5.448,
    max_speed: 9.17,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 136.8,
    elev_low: 106.7,
    upload_id: 10087203562,
    upload_id_str: "10087203562",
    external_id: "27a9c361-8406-440e-b40a-52c5fa58f618-activity.fit",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 113870893, resource_state: 1 },
    name: "Morning Ride",
    distance: 36770.8,
    moving_time: 6966,
    elapsed_time: 8436,
    total_elevation_gain: 163.2,
    type: "Ride",
    sport_type: "Ride",
    workout_type: 12,
    id: 9379107266,
    start_date: "2023-07-03T06:32:42Z",
    start_date_local: "2023-07-03T08:32:42Z",
    timezone: "(GMT+01:00) Europe/Warsaw",
    utc_offset: 7200.0,
    location_city: null,
    location_state: null,
    location_country: "Poland",
    achievement_count: 10,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9379107266",
      summary_polyline:
        "yv|zHc_gmBM|B@jDvRq|F~HuWLYf@_@j@uBhB}DdCsI`@q@@WcAyB?YhImNjGeKxD}FnE`JtCpGZBZw@Ed@j@l@OtA@XxArGT?FNbA|IXlBLHpBu@vO{Dj@]tKd@rAZfBfAnAEdCg@pKgD|Iw@tA_A`AAbCd@l@G|@i@|@wAtA{ApCPjAUt@q@KuAMoCmB_m@KeLDmDl@gRdAmV^wQJc@XP~BvDh@Rv_@R|@CLOQ_EAqEJ{OL}CfKi{AtHmeAl@uEbDwQtT}qAb@aEz@kNRuAGSSCcFqDsBu@sBGKPo@?oAe@oHB}AXeA?UUYJmJeD_o@sVQ^]IIRcBpIg@tA}ApHNx@~ApCbD~HvB`P|@~ND~WJdE?hRKPo@KKXF`IC~INbPI~C?tNYlHQhBw@xVeA`WFXCt@c@hG_@`Ia@hBJzBFfLw@tABxFYzAThDQxENtSLz@FzBKzAH`B@lEApCNpBfC^j@h@bCpDRLn`@Rv@tAVhIMlNF|Fy@`~AMdK_@vBCjFi@hRMvIE^OPBd@iPf`@k@h@_@LoA@MS]RmGIaVNaPfA[IuAXk@Qo@`@aP~@wBA{Dd@wJu@sADuJc@wFrAWb@k@^aDdBH\\ERo@RuAnAM^Jr@g@j@T~@r@~AzKf_@hExM~CfLP~@?`@Ph@n@^N~@rFdPBv@f@hDTbAdBrP@~FOhCYnBt@j@}@|CcCpDGlAH^l@|@l@f@n@bC`@\\`@|AEd@yJrLeGnGYAgAbBSD{Ba@a@l@Fv@S|BoE|EgAz@iBbAkCp@eD`@eEtAoANyAQSX?~@KNoBf@]YEn@mA`@iA@{@u@w@Oo@q@_Ah@sFPyCIw@c@cAj@mJ]_Bo@iBcB}@e@kCwC_@uA[U_@JY`AFbAGt@yAdFkSh_AuGFsDqGk@}AaBWw@nA_AfEw@vG}@|EMdBqA~F}@lHyBbNsCvN}@tBq@t@`@fAD^U~Bq@xBWhBOfG}@~BcAhE[d@}BfHoBpG{ArFM?Xc@vEqPj@_BVg@tAsEn@sCt@mBPyERuBn@oCTmBCa@[eAdAcBhAuD~DmU^uA`@cEb@sCBw@pAgGPoBbAqFf@oEn@_Dj@eBp@g@xAf@j@~AtDdGjGMvPwv@lAoG~AqFHo@t@^TK\\u@zCfDv@Z~A|A`@HRgBEgJN_CDsD",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [51.759980181232095, 18.064381582662463],
    end_latlng: [51.75990281626582, 18.064470598474145],
    average_speed: 5.279,
    max_speed: 11.572,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 137.9,
    elev_low: 100.2,
    upload_id: 10060411703,
    upload_id_str: "10060411703",
    external_id: "9eb68bf1-6b94-4d23-b5f7-c436781158a4-activity.fit",
    from_accepted_tag: false,
    pr_count: 6,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 113870893, resource_state: 1 },
    name: "Morning Ride",
    distance: 31675.1,
    moving_time: 6342,
    elapsed_time: 7202,
    total_elevation_gain: 139.4,
    type: "Ride",
    sport_type: "Ride",
    workout_type: 12,
    id: 9355165261,
    start_date: "2023-06-29T06:40:46Z",
    start_date_local: "2023-06-29T08:40:46Z",
    timezone: "(GMT+01:00) Europe/Warsaw",
    utc_offset: 7200.0,
    location_city: null,
    location_state: null,
    location_country: "Poland",
    achievement_count: 7,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9355165261",
      summary_polyline:
        "mv|zHqdgmBOVD|BM~CDbJ]pBgCyBs@]gAgAuAcBSeAiAa@aG{FaDeEgGoLuIcRoDcFs@_Ba@OuDiFK}@aAa@}A{Bo@e@uBmCqA}Bc@c@HEf@d@pAnBH?hE_R`Fk[vBaRbFgd@AQ]]?OZk@NNHEl@sCnAuCtC_EpCuEL@F_@t@_AnAoAfAi@V@lIwB~By@dEq@fLkD\\g@rCiJr@sCb@_AhCqIxClEtDdIh@h@J`@Ap@z@S^e@vCuNDm@IaAPgA^Yf@?b@u@D[vCaFtA{ApByAhTcLbCW|@{ATQtPwEhAM`@]pKb@~A\\lBhApAKdCg@fLoDrHi@bBcAdACtBf@n@Gx@a@~@wAdBiBrCXrBy@eCau@MsKHcFt@cUfAsXPmKPWPJpCjEPJ|a@HLIOuEAiFF_JN{GlLudBrG{|@j@mEfDcRrT}qA^_DrAmQAWaGcE_Cu@}AGc@VeBe@gBE}ED_CVmCe@gHeCio@wVK`@OGONiBpIg@|AsAvFGn@Jp@bBzC`DrHvBxO~@|OFrXFpB?dTKLo@GIPHxIEpGN~NIbWUpGYdDi@|QsAdZJFEt@U|Be@|GMrE_@`BJzAHxLo@nAMt@HtE[~AT`DK~C@vNNzBChBJzACpDHhIE`DSI}AuBmD_Dw@eAqAiA{@oAgAs@iA}AkEuE}BiDgHaJiAiA_Jg@YN_B]}AA}@p@eAdD[\\kCq@YJsBO{GCSLgAdB_GwAcJmBKHq@pKSjAu@nK?|@k@dG[`Ha@~EAzAGf@c@Ok@lKw@tJWlFgDrd@`@LBLs@rHUdBw@hCmAlCuBhD}ApBmL|PsB`DG\\gBlCs@`Cq@pDy@bGAl@Tz@Sv@SFnAdAh@RpAvALh@pExEg@bB_DjLrDpFd@lAPFJQtBqG`BcG^XfAhC^d@FIY_@DEVh@I[PFKMLJHApClGd@~AG?I_@ANnBhGxErRjCzIn@bDIpANPD^j@h@^xAh@hAlK`^dEpMlDfMT|@Aj@L`@t@p@\\|AbFxNh@|EXpAdB~P@fGOfCWdBZBVT@L{@zCaCvDKdAl@tAr@v@Jf@j@|APDr@|BKd@g@\\Uf@wG|HgHrH[?eA~AQJcCi@a@v@Lp@SzBiFtF}CjBoCp@_D\\aEvAgAN_BUYZ@~@IPuBd@YSGl@{Bd@[Gw@q@y@Qe@u@]JYZaAN{AE{APkDIw@u@a@eD",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [51.75984573550522, 18.06437596678734],
    end_latlng: [51.75988965667784, 18.064468167722225],
    average_speed: 4.994,
    max_speed: 10.972,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 137.9,
    elev_low: 100.5,
    upload_id: 10034544983,
    upload_id_str: "10034544983",
    external_id: "415af737-9ed9-4178-a998-7a72786aa9a8-activity.fit",
    from_accepted_tag: false,
    pr_count: 3,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 113870893, resource_state: 1 },
    name: "Morning Ride",
    distance: 29017.4,
    moving_time: 6460,
    elapsed_time: 7581,
    total_elevation_gain: 117.8,
    type: "Ride",
    sport_type: "Ride",
    workout_type: 10,
    id: 9299594661,
    start_date: "2023-06-20T06:32:00Z",
    start_date_local: "2023-06-20T08:32:00Z",
    timezone: "(GMT+01:00) Europe/Warsaw",
    utc_offset: 7200.0,
    location_city: null,
    location_state: null,
    location_country: "Poland",
    achievement_count: 0,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9299594661",
      summary_polyline:
        "ev|zHudgmBQPBlCMbCH|I[jCmCyBcAi@uCkDS_AkAc@sFqF{CyDqG{LaJsRgDwEc@kAy@q@oD_FCo@_@_@e@OeBaCg@_@yBkCmAwBg@g@JGh@f@lAlBRY|DoPzDkVnDkYxE}b@c@u@\\g@THVuA~AqE|DsF|CeFdBkBjAm@~KaCzQcFhBw@Zk@~@qDjHiUN@l@t@hBjDrDfI\\XJZ?v@NBh@[XWPg@pCqNG_BDc@f@y@l@@dBuDdBuCnCeCnUyLbCU|AwB~S{FnK`@dB`@~A`AhACxCo@~KiDxHm@fBgA|@AbCj@f@Gt@c@tAqBpAsA`C\\nAYt@g@c@mKaBah@M{KFkE|B}n@JsIL}BiCe@Wq@aBoBqEgEgGqGcEsE}@sAaDsDaIoKiLm@yCWu@^m@lAwAlEeBrCEtCKdCCvKMfFFj@GxB?zEN~AFErB|AvAgAr@Org@hBpA[|@w@`BwBPC^}@pBwCL_@TQZ@rDnAIrB?pDB^EXWXWfAN`BEtAGBIh@E~Dm@lENaBNUJb@K`@UtFg@XW`@OCw@iCcBo@uJ}AuDu@gAgAaEUu@_A}H[MK?i@K[}@e@x@p@JACKIFDLSAWw@eDaCeAGuBgBWA{D{Bu@q@S}@RsH@_AM_ANwACcAJqAG{BL{DEuC@sCPmCGeEJuDAaEH{BLw@n@KhC\\z@Qf@n@xEFODDFKJSGCm@l@aB|BeCRChA{B|BcCf@q@?M~DmD|@_BxAeBbDyEjAiAbA_BjHzBpH~Cn@l@OzAJdBC~ALfIs@vA?xF[hBTlCOzCJdJEhEJjAEzBV`BI`GJzGEbAF~ARPdBPj@ZhCxDb@`@x`@Rr@pAVnHKxNFtGy@h{AM~Lc@tCOpN[vHKpHIvAQT@r@gPj`@_Ap@{ADOSKNo^DaTxAk@Oq@^uPbAiBCwDb@mJu@kM]yFvAu@x@kDfBBl@s@XyAnACd@Fb@g@j@@d@fAdClKf^pDbLdEfOV|Bv@p@VdAhFjOj@zEZvA`BdPDhBElDOzBWdBn@\\FRw@pCgC`EIfAr@|Aj@h@v@~B\\Jd@dBBj@_At@Op@gIjJqFxF[AiA`BqC]_@n@H~@GrAOd@kEzE_E`CeCn@}C\\gExAiANuAWYX?~@IPqBf@]QIj@uBd@e@G}@s@q@Me@s@[@Wf@MB{FN{CG{@y@_@aD",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [51.75983726978302, 18.06433942168951],
    end_latlng: [51.75990432500839, 18.064456852152944],
    average_speed: 4.492,
    max_speed: 11.078,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 137.9,
    elev_low: 100.5,
    upload_id: 9975869711,
    upload_id_str: "9975869711",
    external_id: "aeb14501-d859-4c87-bccc-85b83d664f18-activity.fit",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
];
